### ISSUE TITLE
Breaks Safari new Tab handling

### ISSUE THREAD

**Issue by ghost** [infernoboy/JavaScript-Blocker#19]
Hi,

with JavaScript-Blocker and Safari 6.0.5 cmd-click open new tabs always in foreground . Disabling JSB restores normal behavior. Resetting JSB hasn't helped.

Cheers,
Christian

**Comment by infernoboy** [comment]
Are you using the featured marked "EXPERIMENTAL: Enable full referrer blocking"?

**Comment by ghost** [comment]
Yes. Disabling this option worked like a charm. Is there a way to have both? Referrer blocking and open tabs in background?

**Comment by infernoboy** [comment]
I thought I replied to this already... Anyway, you're referring to the fact that a new tab does open, but gains focus instead of leaving the current tab in focus? If so, it would be difficult to implement this without breaking it for other users or implementing an odd setting. There is no way to determine if a user has set tabs to activate upon being created. The only work around is to use the "Open Link in New Tab" context menu item.

**Comment by infernoboy** [comment]
Okay, it took about 5 seconds to implement this new setting. Update 4.0.0 will include a setting "When a new tab opens, make it active". It will be enabled by default. You can turn it off from the Other Features tab of the settings page.
