### ISSUE TITLE
Allow subsequent AJAX POST/GET requests (with monitoring)

### ISSUE THREAD

**Issue by ghost** [infernoboy/JavaScript-Blocker#21]
Please consider modifying the behavior of the "Let me confirm when an AJAX request is allowed to POST or GET information" feature.

I like being informed when these requests are being made and having the ability to deny them. The problem is that they usually come in clusters, so the user is effectively bombarded with several confirmation dialogs in a row.

I think a better way to handle this might be to add a "allow subsequent requests" checkbox or 3rd button to the dialog that pops up.

Once enabled, the "allow subsequent requests" state could be kept active perhaps only for a certain timeframe (several seconds/minutes) or until the user navigates away from the current page.

It would be even better if once the "allow subsequent requests" state is enabled, the user would still be notified when such requests are made (perhaps with a little floating notification in a corner of the browser) but not pestered with a dialog asking to explicit allow them.

Going even further, the floating notification (or whatever) could be made to provide—when clicked or hovered—the history of all such requests made while the "allow subsequent requests" state has been active for the current page.

And finally, if you _really_ wanted to go nuts with that, you could make it to where the user could interact with that history. The user could select individual requests and pull up an interface that would let them configure the extension to allow/disallow similar future requests (maybe with a regex?). I'm thinking something like the current management rule interface.

**Comment by infernoboy** [comment]
The issue with this is that in order to function optimally without running into timeout issues, I have to use a synchronous event which stops all script execution to show the standard browser confirm dialog. This does not allow me to add any special functions; just an OK and Cancel button. However, I can attempt to implement an asynchronous method which will delay the AJAX send() function until the user manually invokes it. JSB already has the inline page alerts feature which I can utilize for this. 

I suppose I _could_ make a rule interface for it, but what would the rule be? The page the AJAX request is POST/GET'ing to/from? Is this what defines a "similar request"?

**Comment by infernoboy** [comment]
Ideas:
    A request is intercepted and an inline-alert is displayed with buttons: Allow, Allow Similar, Deny, Deny Similar
    Allow and Deny are one time actions.
    Allow/Deny Similar will bring up an interface to add a rule. Only the path can be matched for POST requests; parameters will be ignored for purposes of allowing or denying. For GET requests, the rule can include parameter matching as: /get/this?value=.+&for=.+
    Logging the requests will be simple enough, ~~but coming up with a method of displaying the history without some awkward keyboard shortcut is tough.~~ Apparently I completely forgot about the JSB popover: 
![screen-shot-2013-10-13-at-4 46 06-am](https://f.cloud.github.com/assets/25857/1321680/0267605c-33e4-11e3-9a1a-922aed4ec101.png)

So far: 
![screen-shot-2013-10-13-at-4 22 45-am](https://f.cloud.github.com/assets/25857/1321658/8df8c2c6-33e1-11e3-8f37-1781aac0d98c.png)

**Comment by ghost** [comment]
Wow, that's great! Looking good already… :grinning:

I don't want to get too greedy, but how about allowing the user to specify a regular expression for matching "similar requests"? Would that make sense?

**Comment by infernoboy** [comment]
That's already how it's going to work!

Sent from my iPod

On Oct 14, 2013, at 2:20 AM, Darin Morrison notifications@github.com
wrote:

Wow, that's great! Looking good already… [image: :grinning:]

I don't want to get too greedy, but how about allowing the user to specify
a regular expression for matching "similar requests"? Would that make sense?

—
Reply to this email directly or view it on
GitHubhttps://github.com/infernoboy/JavaScript-Blocker/issues/21#issuecomment-26237503
.

**Comment by infernoboy** [comment]
~~If an in-page alert did not appear and instead acted like any other blocked item (i.e. it just will show up as allowed/blocked in the popover), would this be acceptable? While having the ability to allow/deny each individual request as it happens might be nice, it seems to be a bit overkill.~~ Never mind, it appears it was a lot easier to implement than I thought it would be.

I will be reworking the feature to be under the Rules section of the settings page rather than Other Features. It will then include the standard automatic action that you can choose: blacklist only, same host, same domain, nowhere. And if being prompted for each individual request, an "ask me when necessary" option.

**Comment by infernoboy** [comment]
This feature has been implemented as of release 4.0.5, though fixed for Safari 5.1 in 4.0.6.

**Comment by ghost** [comment]
Excellent!

Sorry I didn't get back to your question earlier… but anyway, the way it works now (when select "ask me […]") is great—very close to what I had in mind. So that's already more than I expected :)

I do think it would be a _little_ more convenient if the user could pull up the "Adding a Rule" dialog by directly clicking on the AJAX request popover. Unless I am missing something, the way it works now requires a few extra steps: a) hit Allow/Block on the request, b) pull up the rules editor for the current page, c) find the entry for query just allowed/blocked, d) edit and make a permanent rule. That doesn't take as long as it sounds, but nonetheless, allowing the user to activate the "Adding a Rule" dialog directly over the popover might streamline the process. 

Don't get me wrong—it's a relatively minor thing and I do really appreciate the work you've put into this plugin and the time you spent to implement this feature.

So thanks and keep up the good work!

**Comment by infernoboy** [comment]
I will work on improving this feature but wanted to get out this version quickly as I believe it's a good starting point. Hopefully I can find an elegant solution to adding a rule directly from the inline page dialog. Until then, you're going to have to suffer through the extra clicks!
